"""The pet: Beep, extracted pixel by pixel, standing and breathing.

WHY A PET. The screen recomputes every second, and a grid of static figures
looks identical whether it is measuring or wedged. The pet settles that and
nothing else — which is why `h` hides the engine's commentary but never the
pet.

WHO. Beep, the Southern Hive Prince, from the ArtStation piece where he stands
in the wasteland with a huge weapon over his shoulder. Kenshi's most-loved
character, and cheerful where the rest of that world is not.

EXTRACTED AT NATIVE RESOLUTION, NOT REDRAWN AND NOT REDUCED. The source is a
1000x1000 JPEG whose art is really about 100x100; quantising to 32 colours
first removes the JPEG ringing that otherwise makes every edge unrecoverable.
Beep is 21 wide and 54 tall in that grid, in 17 colours, and he is used at exactly
that size — 28 text rows, nothing scaled.

THE BACKGROUND IS FLOODED FROM THE CROP BORDER, not matched by colour. The
artist reuses the sky tone as a highlight on his jeans and shoulders, so a
global colour match punched holes straight through him; flooding inward from
the frame leaves any interior pixel of the same tone untouched, because it
cannot be reached.

Loose specks left by the crop slicing through his weapon are dropped by
keeping only the largest connected component — at this size they read as dirt
on the screen rather than as a weapon.

RIGID BONES. The figure is split at the neck and the hip into head, torso and
legs, and a frame only ever TRANSLATES those groups. Nothing is scaled,
squashed or cropped, so the head, chest and legs keep their exact height in
every frame. The idle is a breath: the upper body settles one pixel toward the
planted legs and comes back. It moves only DOWN, because moving up would open
a gap at the hip — and the obvious fix for that gap is stretching the torso,
which is precisely what must not happen.

Frame timing lives in the view (``SPRITE_FRAME_S``) and comes from the clock,
so every frame is shown for the same length of time however often the screen
repaints.
"""

from __future__ import annotations

from claude_swap.tui.sprite import Sprite

#: Every colour of the source art, ordered dark to light.
_PALETTE = {
    "a": "#2d2d2a",
    "b": "#47261d",
    "c": "#5b3629",
    "d": "#5c3628",
    "e": "#5c3629",
    "f": "#38475b",
    "g": "#38475c",
    "h": "#38475d",
    "i": "#39475c",
    "j": "#73482d",
    "k": "#74482c",
    "l": "#8c6831",
    "m": "#7288a5",
    "n": "#7388a5",
    "o": "#7388a6",
    "p": "#c49a59",
    "q": "#e9d5a9",
}

_IDLE = (
    (
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....agfa.annga.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        ".....................",
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        ".....................",
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....agfa.annga.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjjappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....agfa.annga.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        ".....................",
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        ".....................",
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
    (
        "......aaaaaaaaaa.....",
        ".....allllllllla.....",
        ".....allllljaaa......",
        ".....allaajpa........",
        ".....ajjqappa........",
        ".....allaappaaaaa..aa",
        "....aallljppa....aa..",
        "...afallljja.........",
        "aa.ajajjljla.........",
        "..aakallljlla........",
        "..aadcaaajaaa........",
        "aajaehgiajja.........",
        "..aaggaappplaa.......",
        ".aoagalppllllja......",
        ".annalljlllljpa..aa..",
        ".annaljlllljpppaa..aa",
        "ajaaaljlllljppla.....",
        ".ajjallllljjalla.....",
        "..aaaljllljanalla....",
        "....aljlljjanalla....",
        "....ajpjjjanbbala....",
        ".....allpambbbapa....",
        ".....apppabbeeapa....",
        ".....allpabeeeapa....",
        ".....apppaeeeeala....",
        "....apllppaeeeala....",
        "...agpppppfaaalla....",
        "...agggggggallla.....",
        "...aggggggggalla.....",
        "...agaggnnngalla.....",
        "...againnnnnaaa......",
        "...agfagnnnga........",
        "...aggaggnnna........",
        "...agggannnna........",
        "...agggagnngga.......",
        "....aggaannnna.......",
        "....aggaaggnna.......",
        "....agfa.annga.......",
        "....alca.agggga......",
        "....alca..afgga......",
        ".....ala..appla......",
        ".....ala...apla......",
        ".....aaa...appa......",
        ".....aea...appa......",
        ".....aka....apla.....",
        "......aa....alla.....",
        "......aa....alja.....",
        "......aa.a..ajja.....",
        ".....alaaa..ajja.....",
        ".a..alcca...aja......",
        ".aaaaaaa....aja......",
        "............aja......",
        "............aja......",
        "............aa.......",
        ".....................",
        ".....................",
    ),
)

#: Standing. Auto off.
WATCHING = Sprite(palette=_PALETTE, frames=_IDLE)

#: Standing, same body. Auto on — the view dims the idle state instead, so the
#: armed pet is simply the brighter one.
WORKING = Sprite(palette=_PALETTE, frames=_IDLE)
